import{a as m,S as d,i as a}from"./assets/vendor-Dy2ZTtfi.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const f="https://pixabay.com/api/",p="51361709-3ae7eddc83ad637b7c3fc8345";function g(i){const o=new URLSearchParams({key:p,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9});return m.get(`${f}?${o}`).then(r=>r.data)}let l=null;function h(i){return i.map(({largeImageURL:o,webformatURL:r,tags:s,...e})=>{const t=["Likes","Views","Comments","Downloads"].map(n=>`
            <li class="images-info-item">
              <h3 class="images-info-subtitle">${n}</h3>
              <p class="images-info-value">${e[n.toLowerCase()]}</p>
            </li>`).join("");return`
        <li class="gallery-item">
          <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${r}" alt="${s}" />
            <ul class="images-info-list">${t}</ul>
          </a>
        </li>`}).join("")}function y(){l?l.refresh():l=new d(".js-gallery a",{captionsData:"alt",captionDelay:500,doubleTapZoom:1.2,maxZoom:4,disableScroll:!0})}const L=document.querySelector(".js-form"),u=document.querySelector(".js-gallery"),c=document.querySelector(".loader");L.addEventListener("submit",b);function b(i){i.preventDefault(),c.classList.remove("hidden");const r=i.currentTarget.elements["search-text"].value.trim();if(!r){a.error({title:"Error",message:"field must not be empty",position:"center"}),c.classList.add("hidden");return}u.innerHTML="",g(r).then(s=>{s.hits.length?(u.innerHTML=h(s.hits),y()):a.warning({title:"⚠️ Warning",message:`Sorry, there are no images matching your "${r}". Please try again!`,position:"center",timeout:4e3})}).catch(s=>{a.error({title:"Error",message:`${s.message}`,position:"center"})}).finally(()=>{i.target.reset(),c.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
