import{a as m,S as f,i as n}from"./assets/vendor-Dy2ZTtfi.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const d="https://pixabay.com/api/",p="51361709-3ae7eddc83ad637b7c3fc8345";function g(s){const i=new URLSearchParams({key:p,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:9});return m.get(`${d}?${i}`).then(r=>r.data)}let l=null;function h(s){return s.map(({largeImageURL:i,webformatURL:r,tags:o,...e})=>{const t=["Likes","Views","Comments","Downloads"].map(a=>`
            <li class="images-info-item">
              <h3 class="images-info-subtitle">${a}</h3>
              <p class="images-info-value">${e[a.toLowerCase()]}</p>
            </li>`).join("");return`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${r}" alt="${o}" />
            <ul class="images-info-list">${t}</ul>
          </a>
        </li>`}).join("")}function y(){l?l.refresh():l=new f(".js-gallery a",{captionsData:"alt",captionDelay:500,doubleTapZoom:1.2,maxZoom:4,disableScroll:!0})}const L=document.querySelector(".js-form"),c=document.querySelector(".js-gallery"),u=document.querySelector(".loader");L.addEventListener("submit",b);function b(s){s.preventDefault();const r=s.currentTarget.elements["search-text"].value.trim();if(!r){n.error({title:"Error",message:"field must not be empty",position:"topRight"});return}c.innerHTML="",u.classList.remove("hidden"),g(r).then(o=>{o.hits.length?(c.innerHTML=h(o.hits),y()):n.warning({title:"⚠️ Warning",message:`Sorry, there are no images matching your "${r}". Please try again!`,position:"topRight",timeout:4e3})}).catch(o=>{n.error({title:"Error",message:`${o.message}`,position:"topRight"})}).finally(()=>{s.target.reset(),u.classList.add("hidden")})}
//# sourceMappingURL=index.js.map
